### ISSUE TITLE
Subsequent messages from Wit.ai

### ISSUE THREAD

**Issue by rolero** [froesmatheus/wit.net#1]
I have the challenge that I have subsequent messages coming from wit.ai. For example, the bot first says something back and then initiates a function with any user response in between. What is the best way to handle and receives these real-time messages using this library?

**Comment by froesmatheus** [comment]
Hi @rolero, can you please provide an example of this? I don't think I get it

**Comment by rolero** [comment]
For example:

1. User says "hi"
2. Bot says "Hi welcome"
3. Bot calls function

I am not getting the second message from the bot because there is no user interaction in between.


![issue](https://cloud.githubusercontent.com/assets/2805313/23291473/e74b72b6-fa93-11e6-92c0-dabec5206ca3.png)

**Comment by rolero** [comment]
Hi, any update?

**Comment by froesmatheus** [comment]
Hi @rolero, sorry for my long response delay, I was not receiving notifications about this thread. What I don't understand about your example is that you're executing an action after a bot response, but you're not using the context keys that is the result of the action. I think you should do something like this:

![capturar](https://cloud.githubusercontent.com/assets/8764566/23608247/42405f3c-0247-11e7-95d7-8c80ec82b1b5.PNG)

**Comment by froesmatheus** [comment]
@rolero, after seeing your challenge, I realized that the current SDK is not able to handle multiple messages coming from the bot at the same time. This happens because the bot response is only returning a string containing the response. One of the possible solutions would be, instead of returning only one value, it returns a list of responses, but that would break current solutions. I will try to implement this feature as soon as possible. Thanks!

**Comment by froesmatheus** [comment]
Hi @rolero , I updated the nuget package with the recent changes. Make sure you're using the 'RunActions' method. Please give me feedback about the new version, thanks!

**Comment by froesmatheus** [comment]
Hi @rolero, any news?
